<div class="outer">
		<div class="menu">
			<ul>
				<li><a href="../user/edituser.php">My Profile</a></li>
				<li><a href="../article/addarticle.php">Add Article</a></li>
				<li><a href="../article/listarticle.php">My Blogs</a></li>
				<li><a href="../photo/listalbum.php">My Photos</a></li>
				<li><a href="../photo/addPhoto.php">Add Photos</a></li>
				<li><a href="../map/listlocation.php">My Travel Lounge</a></li>
				<li><a href="#">Support</a></li>
			</ul>
		</div>
</div>
